function cap(id, name, description, parentId = null) {
  return {
    id, name, description,
    parentCapabilityId: parentId,
    status:             'active',
    subCapabilities:    [],
    owners:             [],
    processes:          [],
    valueStreams:       [],
    createdAt:          null,
    createdBy:          null,
    updatedAt:          null,
    updatedBy:          null,
  }
}

const CAPABILITIES = [

  // ─── L1: Product Development ────────────────────────────────────────────────
  cap('cap-l1-product-development', 'Product Development',
    'The ability to design, build, and continuously improve software products that deliver customer value.'),

  cap('cap-l2-product-planning', 'Product Planning',
    'Defines product strategy, roadmap, and feature prioritisation to align engineering with business goals.',
    'cap-l1-product-development'),
  cap('cap-l3-product-roadmap-management', 'Product Roadmap Management',
    'Maintain and communicate the product roadmap across stakeholders.', 'cap-l2-product-planning'),
  cap('cap-l3-feature-prioritisation', 'Feature Prioritisation',
    'Evaluate and rank features based on impact, effort, and strategic fit.', 'cap-l2-product-planning'),
  cap('cap-l3-release-planning', 'Release Planning',
    'Coordinate the scope and schedule of product releases.', 'cap-l2-product-planning'),

  cap('cap-l2-software-engineering', 'Software Engineering',
    'Capability to design, build, and maintain production software across the full stack.',
    'cap-l1-product-development'),
  cap('cap-l3-frontend-engineering', 'Frontend Engineering',
    'Build and maintain user-facing interfaces and web applications.', 'cap-l2-software-engineering'),
  cap('cap-l3-backend-engineering', 'Backend Engineering',
    'Design and operate server-side systems, services, and data pipelines.', 'cap-l2-software-engineering'),
  cap('cap-l3-api-design', 'API Design',
    'Define and govern internal and external API contracts.', 'cap-l2-software-engineering'),

  cap('cap-l2-product-quality-management', 'Product Quality Management',
    'Ensures software meets quality standards through structured testing and defect management.',
    'cap-l1-product-development'),
  cap('cap-l3-qa-automation', 'QA Automation',
    'Automate regression and functional test suites across the product surface.', 'cap-l2-product-quality-management'),
  cap('cap-l3-bug-tracking', 'Bug Tracking',
    'Capture, triage, and manage defects through to resolution.', 'cap-l2-product-quality-management'),
  cap('cap-l3-performance-testing', 'Performance Testing',
    'Measure and validate system performance under load.', 'cap-l2-product-quality-management'),

  cap('cap-l2-code-analytics', 'Code Analytics',
    'Provides visibility into codebase health, coverage, and dependency risk.',
    'cap-l1-product-development'),
  cap('cap-l3-static-code-analysis', 'Static Code Analysis',
    'Detect code smells, complexity, and anti-patterns before runtime.', 'cap-l2-code-analytics'),
  cap('cap-l3-code-coverage-reporting', 'Code Coverage Reporting',
    'Track the proportion of code exercised by automated tests.', 'cap-l2-code-analytics'),
  cap('cap-l3-dependency-analysis', 'Dependency Analysis',
    'Audit third-party dependencies for risk, licence, and version drift.', 'cap-l2-code-analytics'),

  cap('cap-l2-code-security', 'Code Security',
    'Identifies and remediates security vulnerabilities in application code.',
    'cap-l1-product-development'),
  cap('cap-l3-vulnerability-scanning', 'Vulnerability Scanning',
    'Continuously scan code and dependencies for known CVEs.', 'cap-l2-code-security'),
  cap('cap-l3-penetration-testing', 'Penetration Testing',
    'Conduct simulated attacks to find exploitable weaknesses.', 'cap-l2-code-security'),
  cap('cap-l3-security-code-review', 'Security Code Review',
    'Review code changes for security issues before merge.', 'cap-l2-code-security'),

  cap('cap-l2-ui-ux-design', 'UI/UX Design',
    'Creates user experiences that are usable, accessible, and aligned with brand standards.',
    'cap-l1-product-development'),
  cap('cap-l3-user-research', 'User Research',
    'Gather qualitative and quantitative insight into user needs and behaviours.', 'cap-l2-ui-ux-design'),
  cap('cap-l3-wireframing-prototyping', 'Wireframing & Prototyping',
    'Create low and high-fidelity prototypes to validate design concepts.', 'cap-l2-ui-ux-design'),
  cap('cap-l3-design-systems', 'Design Systems',
    'Maintain a shared component library and visual language across products.', 'cap-l2-ui-ux-design'),

  cap('cap-l2-source-code-management', 'Source Code Management',
    'Governs how code is versioned, branched, reviewed, and merged.',
    'cap-l1-product-development'),
  cap('cap-l3-version-control', 'Version Control',
    'Track and manage code changes across branches and releases.', 'cap-l2-source-code-management'),
  cap('cap-l3-branch-management', 'Branch Management',
    'Define and enforce branching strategies for feature and release work.', 'cap-l2-source-code-management'),
  cap('cap-l3-code-review', 'Code Review',
    'Structured peer review process to maintain code quality and knowledge sharing.', 'cap-l2-source-code-management'),

  // ─── L1: Platform & Service Operations ──────────────────────────────────────
  cap('cap-l1-platform-operations', 'Platform & Service Operations',
    'The ability to reliably build, deploy, configure, and operate the software platform at scale.'),

  cap('cap-l2-software-release-management', 'Software Release Management',
    'Governs the packaging, scheduling, and delivery of software releases to production.',
    'cap-l1-platform-operations'),
  cap('cap-l3-release-automation', 'Release Automation',
    'Automate the end-to-end pipeline from build artefact to production deployment.', 'cap-l2-software-release-management'),
  cap('cap-l3-version-management', 'Version Management',
    'Track and control software versions across environments.', 'cap-l2-software-release-management'),
  cap('cap-l3-rollback-management', 'Rollback Management',
    'Safely revert to a previous release when a deployment introduces issues.', 'cap-l2-software-release-management'),

  cap('cap-l2-infrastructure-services', 'Infrastructure Services',
    'Provisions and manages the underlying compute, storage, and network resources.',
    'cap-l1-platform-operations'),
  cap('cap-l3-cloud-infrastructure', 'Cloud Infrastructure',
    'Manage cloud resources, scaling, and cost across providers.', 'cap-l2-infrastructure-services'),
  cap('cap-l3-network-management', 'Network Management',
    'Configure and monitor network topology, DNS, and connectivity.', 'cap-l2-infrastructure-services'),
  cap('cap-l3-server-operations', 'Server Operations',
    'Provision, patch, and maintain server fleet health.', 'cap-l2-infrastructure-services'),

  cap('cap-l2-platform-configuration', 'Platform Configuration',
    'Manages environment configuration, feature flags, and settings across the platform.',
    'cap-l1-platform-operations'),
  cap('cap-l3-environment-management', 'Environment Management',
    'Maintain parity and governance across dev, staging, and production environments.', 'cap-l2-platform-configuration'),
  cap('cap-l3-configuration-management', 'Configuration Management',
    'Store, version, and distribute application configuration securely.', 'cap-l2-platform-configuration'),
  cap('cap-l3-feature-flags', 'Feature Flags',
    'Control feature availability at runtime without code deployments.', 'cap-l2-platform-configuration'),

  cap('cap-l2-platform-analytics', 'Platform Analytics & Telemetry',
    'Collects and surfaces platform health metrics, logs, and performance signals.',
    'cap-l1-platform-operations'),
  cap('cap-l3-metrics-collection', 'Metrics Collection',
    'Instrument services to emit and aggregate operational metrics.', 'cap-l2-platform-analytics'),
  cap('cap-l3-log-management', 'Log Management',
    'Centralise, search, and retain application and infrastructure logs.', 'cap-l2-platform-analytics'),
  cap('cap-l3-alerting', 'Alerting',
    'Define thresholds and notification channels for operational anomalies.', 'cap-l2-platform-analytics'),

  cap('cap-l2-platform-governance', 'Platform Governance',
    'Establishes policies, standards, and controls for platform operations.',
    'cap-l1-platform-operations'),
  cap('cap-l3-sla-management', 'SLA Management',
    'Define, monitor, and report on platform service-level agreements.', 'cap-l2-platform-governance'),
  cap('cap-l3-change-management', 'Change Management',
    'Control and audit changes to production systems to minimise risk.', 'cap-l2-platform-governance'),
  cap('cap-l3-capacity-planning', 'Capacity Planning',
    'Forecast resource requirements and plan ahead for growth.', 'cap-l2-platform-governance'),

  // ─── L1: Account Management ──────────────────────────────────────────────────
  cap('cap-l1-account-management', 'Account Management',
    'The ability to manage the full commercial lifecycle of customer accounts from pipeline to renewal.'),

  cap('cap-l2-account-analytics', 'Account Analytics',
    'Provides commercial intelligence on account health, pipeline, and performance.',
    'cap-l1-account-management'),
  cap('cap-l3-sales-performance-analytics', 'Sales Performance Analytics',
    'Track individual and team sales performance against targets.', 'cap-l2-account-analytics'),
  cap('cap-l3-pipeline-analytics', 'Pipeline Analytics',
    'Analyse pipeline velocity, coverage, and stage conversion rates.', 'cap-l2-account-analytics'),
  cap('cap-l3-win-loss-analysis', 'Win/Loss Analysis',
    'Understand the reasons behind deal outcomes to improve go-to-market.', 'cap-l2-account-analytics'),

  cap('cap-l2-account-database', 'Account Database & List Services',
    'Maintains accurate, enriched account and contact data to support sales motions.',
    'cap-l1-account-management'),
  cap('cap-l3-crm-data-management', 'CRM Data Management',
    'Govern CRM data quality, deduplication, and field standards.', 'cap-l2-account-database'),
  cap('cap-l3-contact-lists', 'Contact Lists',
    'Build and maintain segmented contact lists for sales outreach.', 'cap-l2-account-database'),
  cap('cap-l3-data-enrichment', 'Data Enrichment',
    'Augment account and contact records with third-party firmographic data.', 'cap-l2-account-database'),

  cap('cap-l2-lead-opportunity', 'Lead & Opportunity Management',
    'Manages the qualification and progression of leads and opportunities through the sales funnel.',
    'cap-l1-account-management'),
  cap('cap-l3-lead-scoring', 'Lead Scoring',
    'Score inbound leads by fit and intent to prioritise sales effort.', 'cap-l2-lead-opportunity'),
  cap('cap-l3-opportunity-tracking', 'Opportunity Tracking',
    'Track deal progress, activities, and next steps in the CRM.', 'cap-l2-lead-opportunity'),
  cap('cap-l3-deal-management', 'Deal Management',
    'Manage deal structure, commercial terms, and approval workflows.', 'cap-l2-lead-opportunity'),

  cap('cap-l2-forecasting', 'Forecasting & Performance Management',
    'Produces revenue forecasts and monitors commercial performance against plan.',
    'cap-l1-account-management'),
  cap('cap-l3-revenue-forecasting', 'Revenue Forecasting',
    'Generate and maintain accurate pipeline-based revenue forecasts.', 'cap-l2-forecasting'),
  cap('cap-l3-quota-management', 'Quota Management',
    'Set, communicate, and track sales quotas by rep and team.', 'cap-l2-forecasting'),
  cap('cap-l3-performance-dashboards', 'Performance Dashboards',
    'Provide real-time commercial dashboards for leadership and sellers.', 'cap-l2-forecasting'),

  cap('cap-l2-quotes-proposals', 'Quotes & Proposals',
    'Manages the creation, approval, and delivery of pricing quotes and commercial proposals.',
    'cap-l1-account-management'),
  cap('cap-l3-quote-generation', 'Quote Generation',
    'Produce accurate, compliant commercial quotes from approved rate cards.', 'cap-l2-quotes-proposals'),
  cap('cap-l3-proposal-management', 'Proposal Management',
    'Create and manage tailored sales proposals for enterprise opportunities.', 'cap-l2-quotes-proposals'),
  cap('cap-l3-contract-terms', 'Contract Terms',
    'Negotiate and manage commercial and legal terms within proposals.', 'cap-l2-quotes-proposals'),

  cap('cap-l2-technical-support', 'Technical Product Support',
    'Provides technical assistance to customers experiencing product issues.',
    'cap-l1-account-management'),
  cap('cap-l3-customer-support-tickets', 'Customer Support Tickets',
    'Receive, triage, and resolve inbound customer support requests.', 'cap-l2-technical-support'),
  cap('cap-l3-knowledge-base', 'Knowledge Base',
    'Maintain a self-service repository of product documentation and FAQs.', 'cap-l2-technical-support'),
  cap('cap-l3-escalation-management', 'Escalation Management',
    'Manage escalation paths for critical customer issues.', 'cap-l2-technical-support'),

  cap('cap-l2-partner-management', 'Partner Management',
    'Manages the recruitment, enablement, and performance of channel and technology partners.',
    'cap-l1-account-management'),
  cap('cap-l3-partner-onboarding', 'Partner Onboarding',
    'Onboard new partners with contracts, training, and tooling access.', 'cap-l2-partner-management'),
  cap('cap-l3-partner-programme', 'Partner Programme',
    'Define and administer partner tiers, incentives, and benefits.', 'cap-l2-partner-management'),
  cap('cap-l3-partner-portal', 'Partner Portal',
    'Operate a self-service portal for partner resources and deal registration.', 'cap-l2-partner-management'),

  cap('cap-l2-supplier-management', 'Supplier Management & Procurement',
    'Governs the selection, contracting, and management of third-party suppliers.',
    'cap-l1-account-management'),
  cap('cap-l3-vendor-evaluation', 'Vendor Evaluation',
    'Assess and shortlist vendors against defined criteria and risk profile.', 'cap-l2-supplier-management'),
  cap('cap-l3-purchase-orders', 'Purchase Orders',
    'Raise, approve, and track purchase orders with suppliers.', 'cap-l2-supplier-management'),
  cap('cap-l3-supplier-contracts', 'Supplier Contracts',
    'Manage supplier contract lifecycle including renewals and SLAs.', 'cap-l2-supplier-management'),

  // ─── L1: Enterprise Support ──────────────────────────────────────────────────
  cap('cap-l1-enterprise-support', 'Enterprise Support',
    'The ability to operate and sustain the internal functions that keep the business running efficiently.'),

  cap('cap-l2-contract-management', 'Contract Management',
    'Manages the full lifecycle of internal and external contracts.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-contract-authoring', 'Contract Authoring',
    'Draft contracts from standard templates with appropriate legal review.', 'cap-l2-contract-management'),
  cap('cap-l3-contract-lifecycle', 'Contract Lifecycle',
    'Track contracts through execution, amendment, renewal, and termination.', 'cap-l2-contract-management'),
  cap('cap-l3-contract-repository', 'Contract Repository',
    'Maintain a searchable, auditable central store of all agreements.', 'cap-l2-contract-management'),

  cap('cap-l2-travel-management', 'Travel Management',
    'Manages business travel booking, policy compliance, and expenses.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-travel-booking', 'Travel Booking',
    'Book flights, hotels, and ground transport within policy.', 'cap-l2-travel-management'),
  cap('cap-l3-travel-policy', 'Travel Policy',
    'Define and enforce travel spend policies and approval thresholds.', 'cap-l2-travel-management'),
  cap('cap-l3-expense-reporting', 'Expense Reporting',
    'Submit, review, and reimburse employee travel and business expenses.', 'cap-l2-travel-management'),

  cap('cap-l2-facility-management', 'Facility Management & Services',
    'Operates and maintains physical workplaces and associated employee services.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-workplace-services', 'Workplace Services',
    'Provide day-to-day workplace support including catering, mail, and reception.', 'cap-l2-facility-management'),
  cap('cap-l3-office-management', 'Office Management',
    'Plan and manage office layouts, seating, and space allocation.', 'cap-l2-facility-management'),
  cap('cap-l3-maintenance', 'Maintenance',
    'Schedule and execute maintenance of facilities, equipment, and infrastructure.', 'cap-l2-facility-management'),

  cap('cap-l2-project-delivery', 'Project Delivery',
    'Ensures cross-functional projects are planned, resourced, and delivered on time.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-project-planning', 'Project Planning',
    'Define project scope, milestones, dependencies, and success criteria.', 'cap-l2-project-delivery'),
  cap('cap-l3-resource-allocation', 'Resource Allocation',
    'Assign people and budget to projects based on priority and availability.', 'cap-l2-project-delivery'),
  cap('cap-l3-milestone-tracking', 'Milestone Tracking',
    'Monitor and report on project milestones, blockers, and completion.', 'cap-l2-project-delivery'),

  cap('cap-l2-relationship-management', 'Relationship Management',
    'Manages strategic relationships with stakeholders, executives, and partners.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-stakeholder-management', 'Stakeholder Management',
    'Identify and engage internal and external stakeholders in key decisions.', 'cap-l2-relationship-management'),
  cap('cap-l3-executive-engagement', 'Executive Engagement',
    'Manage executive sponsor relationships and steering-level communications.', 'cap-l2-relationship-management'),
  cap('cap-l3-partnership-development', 'Partnership Development',
    'Identify and develop strategic partnerships aligned to business goals.', 'cap-l2-relationship-management'),

  cap('cap-l2-reporting', 'Reporting',
    'Produces structured, repeatable management and operational reports.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-management-reporting', 'Management Reporting',
    'Deliver regular performance reports to leadership and the board.', 'cap-l2-reporting'),
  cap('cap-l3-kpi-dashboards', 'KPI Dashboards',
    'Maintain live dashboards tracking company and team KPIs.', 'cap-l2-reporting'),
  cap('cap-l3-ad-hoc-analysis', 'Ad-hoc Analysis',
    'Respond to one-off analytical questions from business stakeholders.', 'cap-l2-reporting'),

  cap('cap-l2-employee-productivity', 'Employee Productivity',
    'Provides tools and processes that enable employees to work effectively.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-collaboration-tools', 'Collaboration Tools',
    'Manage messaging, document collaboration, and team workspace tooling.', 'cap-l2-employee-productivity'),
  cap('cap-l3-workplace-apps', 'Workplace Apps',
    'Administer approved productivity applications and their integrations.', 'cap-l2-employee-productivity'),
  cap('cap-l3-document-management', 'Document Management',
    'Store, version, and govern internal documents and records.', 'cap-l2-employee-productivity'),

  cap('cap-l2-content-sharing', 'Content Sharing',
    'Enables employees to find, store, and distribute internal knowledge assets.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-document-storage', 'Document Storage',
    'Provide scalable, searchable storage for company documents and files.', 'cap-l2-content-sharing'),
  cap('cap-l3-knowledge-management', 'Knowledge Management',
    'Capture and organise institutional knowledge for reuse across the organisation.', 'cap-l2-content-sharing'),
  cap('cap-l3-asset-library', 'Asset Library',
    'Manage brand and marketing assets in a shared, governed library.', 'cap-l2-content-sharing'),

  cap('cap-l2-online-conferencing', 'Online Conferencing',
    'Provides virtual meeting and event capabilities for internal and external audiences.',
    'cap-l1-enterprise-support'),
  cap('cap-l3-video-meetings', 'Video Meetings',
    'Support synchronous video calls for internal collaboration.', 'cap-l2-online-conferencing'),
  cap('cap-l3-webinars', 'Webinars',
    'Host external-facing webinar events with registration and recording.', 'cap-l2-online-conferencing'),
  cap('cap-l3-virtual-events', 'Virtual Events',
    'Deliver large-scale virtual conferences and product events.', 'cap-l2-online-conferencing'),

  // ─── L1: Demand Generation ───────────────────────────────────────────────────
  cap('cap-l1-demand-generation', 'Demand Generation',
    'The ability to create awareness, generate pipeline, and drive qualified leads into the sales funnel.'),

  cap('cap-l2-campaign-management', 'Campaign Management',
    'Plans, executes, and measures multi-channel marketing campaigns.',
    'cap-l1-demand-generation'),
  cap('cap-l3-campaign-planning', 'Campaign Planning',
    'Define campaign objectives, audience, channels, and success metrics.', 'cap-l2-campaign-management'),
  cap('cap-l3-campaign-execution', 'Campaign Execution',
    'Activate campaigns across paid, owned, and earned channels.', 'cap-l2-campaign-management'),
  cap('cap-l3-campaign-analytics', 'Campaign Analytics',
    'Measure campaign performance and attribute pipeline to marketing activity.', 'cap-l2-campaign-management'),

  cap('cap-l2-social-engagement', 'Social Engagement',
    'Builds brand presence and community on social media platforms.',
    'cap-l1-demand-generation'),
  cap('cap-l3-social-media-management', 'Social Media Management',
    'Plan, publish, and monitor content across social channels.', 'cap-l2-social-engagement'),
  cap('cap-l3-community-management', 'Community Management',
    'Build and engage user communities around the product and brand.', 'cap-l2-social-engagement'),
  cap('cap-l3-social-listening', 'Social Listening',
    'Monitor brand mentions, sentiment, and competitive conversation online.', 'cap-l2-social-engagement'),

  cap('cap-l2-website-management', 'Website Management',
    'Owns and operates the corporate website as a demand generation and brand asset.',
    'cap-l1-demand-generation'),
  cap('cap-l3-content-management', 'Content Management',
    'Create, publish, and maintain website content across pages and blogs.', 'cap-l2-website-management'),
  cap('cap-l3-technical-seo', 'Technical SEO',
    'Optimise site structure, speed, and crawlability for search engine ranking.', 'cap-l2-website-management'),
  cap('cap-l3-web-analytics', 'Web Analytics',
    'Track visitor behaviour, conversion funnels, and traffic sources.', 'cap-l2-website-management'),

  cap('cap-l2-seo', 'Search Engine Optimisation',
    'Improves organic search visibility through on-page, technical, and off-page tactics.',
    'cap-l1-demand-generation'),
  cap('cap-l3-keyword-research', 'Keyword Research',
    'Identify high-value search terms aligned to buyer intent and product positioning.', 'cap-l2-seo'),
  cap('cap-l3-on-page-seo', 'On-page SEO',
    'Optimise content, meta data, and internal linking for target keywords.', 'cap-l2-seo'),
  cap('cap-l3-link-building', 'Link Building',
    'Acquire high-quality backlinks to improve domain authority.', 'cap-l2-seo'),

  cap('cap-l2-event-marketing', 'Event Marketing',
    'Designs and delivers marketing events that generate pipeline and brand awareness.',
    'cap-l1-demand-generation'),
  cap('cap-l3-event-planning', 'Event Planning',
    'Manage logistics, budget, and timeline for marketing events.', 'cap-l2-event-marketing'),
  cap('cap-l3-event-registration', 'Event Registration',
    'Handle attendee registration, communications, and attendance tracking.', 'cap-l2-event-marketing'),
  cap('cap-l3-event-analytics', 'Event Analytics',
    'Measure event ROI and pipeline contribution post-event.', 'cap-l2-event-marketing'),

  cap('cap-l2-customer-value-propositions', 'Customer Value Propositions',
    'Develops messaging and positioning that clearly communicates the product value.',
    'cap-l1-demand-generation'),
  cap('cap-l3-messaging-strategy', 'Messaging Strategy',
    'Define core messaging pillars aligned to customer segments and buying stages.', 'cap-l2-customer-value-propositions'),
  cap('cap-l3-value-communication', 'Value Communication',
    'Create content that articulates ROI and business outcomes for buyers.', 'cap-l2-customer-value-propositions'),
  cap('cap-l3-competitive-positioning', 'Competitive Positioning',
    'Define and maintain differentiated positioning against key competitors.', 'cap-l2-customer-value-propositions'),

  cap('cap-l2-advertising', 'Advertising',
    'Manages paid digital advertising to drive awareness and top-of-funnel pipeline.',
    'cap-l1-demand-generation'),
  cap('cap-l3-paid-search', 'Paid Search',
    'Run and optimise PPC campaigns on search engines.', 'cap-l2-advertising'),
  cap('cap-l3-display-advertising', 'Display Advertising',
    'Manage programmatic and direct display ad placements.', 'cap-l2-advertising'),
  cap('cap-l3-social-advertising', 'Social Advertising',
    'Execute paid social campaigns on LinkedIn, Meta, and other platforms.', 'cap-l2-advertising'),

  cap('cap-l2-email-marketing', 'Email Marketing',
    'Delivers targeted email programmes to nurture leads and engage customers.',
    'cap-l1-demand-generation'),
  cap('cap-l3-email-campaign-management', 'Email Campaign Management',
    'Build, send, and report on targeted email campaigns.', 'cap-l2-email-marketing'),
  cap('cap-l3-list-management', 'List Management',
    'Manage subscriber lists, segmentation, and data hygiene.', 'cap-l2-email-marketing'),
  cap('cap-l3-email-analytics', 'Email Analytics',
    'Track open rates, click-throughs, and pipeline influence from email programmes.', 'cap-l2-email-marketing'),

  // ─── L1: People Operations ───────────────────────────────────────────────────
  cap('cap-l1-people-operations', 'People Operations',
    'The ability to attract, develop, retain, and support the people who make the organisation run.'),

  cap('cap-l2-salary-commissions', 'Salary & Commissions',
    'Manages compensation including base salaries, variable pay, and commission schemes.',
    'cap-l1-people-operations'),
  cap('cap-l3-payroll-processing', 'Payroll Processing',
    'Process accurate, compliant payroll for all employees on schedule.', 'cap-l2-salary-commissions'),
  cap('cap-l3-commission-calculations', 'Commission Calculations',
    'Calculate and pay sales commissions against defined attainment rules.', 'cap-l2-salary-commissions'),
  cap('cap-l3-salary-benchmarking', 'Salary Benchmarking',
    'Benchmark compensation against market data to maintain competitiveness.', 'cap-l2-salary-commissions'),

  cap('cap-l2-employee-onboarding', 'Employee Onboarding',
    'Ensures new hires are set up, oriented, and productive from day one.',
    'cap-l1-people-operations'),
  cap('cap-l3-pre-boarding', 'Pre-boarding',
    'Complete administrative and access setup before the employee starts.', 'cap-l2-employee-onboarding'),
  cap('cap-l3-orientation', 'Orientation',
    'Introduce new hires to the company culture, team, and ways of working.', 'cap-l2-employee-onboarding'),
  cap('cap-l3-new-hire-documentation', 'New Hire Documentation',
    'Collect and store required employment documentation at the point of joining.', 'cap-l2-employee-onboarding'),

  cap('cap-l2-training-education', 'Training & Education',
    'Provides structured learning opportunities to develop employee skills and knowledge.',
    'cap-l1-people-operations'),
  cap('cap-l3-learning-management', 'Learning Management',
    'Administer the LMS, course catalogue, and training completion tracking.', 'cap-l2-training-education'),
  cap('cap-l3-course-development', 'Course Development',
    'Create and maintain internal training content and programmes.', 'cap-l2-training-education'),
  cap('cap-l3-certification-management', 'Certification Management',
    'Track employee professional certifications and support renewal.', 'cap-l2-training-education'),

  cap('cap-l2-recruitment-hiring', 'Recruitment & Hiring',
    'Attracts and selects qualified candidates to fill open roles.',
    'cap-l1-people-operations'),
  cap('cap-l3-job-posting', 'Job Posting',
    'Publish and manage job listings across internal and external channels.', 'cap-l2-recruitment-hiring'),
  cap('cap-l3-candidate-screening', 'Candidate Screening',
    'Review applications and conduct initial screens to qualify candidates.', 'cap-l2-recruitment-hiring'),
  cap('cap-l3-interview-management', 'Interview Management',
    'Coordinate interview panels, feedback, and hiring decisions.', 'cap-l2-recruitment-hiring'),

  cap('cap-l2-hr-analytics', 'HR Analytics & Reporting',
    'Provides workforce data and insight to inform people strategy decisions.',
    'cap-l1-people-operations'),
  cap('cap-l3-workforce-analytics', 'Workforce Analytics',
    'Analyse headcount, attrition, diversity, and workforce composition trends.', 'cap-l2-hr-analytics'),
  cap('cap-l3-hr-kpi-reporting', 'HR KPI Reporting',
    'Report on people KPIs including eNPS, time-to-hire, and retention rate.', 'cap-l2-hr-analytics'),
  cap('cap-l3-headcount-planning', 'Headcount Planning',
    'Forecast and plan headcount requirements by function and quarter.', 'cap-l2-hr-analytics'),

  cap('cap-l2-talent-management', 'Talent Management',
    'Develops and retains high-performing employees through structured career processes.',
    'cap-l1-people-operations'),
  cap('cap-l3-performance-management', 'Performance Management',
    'Run structured performance review cycles and goal-setting processes.', 'cap-l2-talent-management'),
  cap('cap-l3-succession-planning', 'Succession Planning',
    'Identify and develop successors for critical leadership roles.', 'cap-l2-talent-management'),
  cap('cap-l3-career-development', 'Career Development',
    'Provide frameworks and conversations to support employee career growth.', 'cap-l2-talent-management'),

  cap('cap-l2-employee-data', 'Employee Data Management',
    'Maintains accurate, compliant employee records across the employment lifecycle.',
    'cap-l1-people-operations'),
  cap('cap-l3-hr-records-management', 'HR Records Management',
    'Store and maintain employment records in compliance with data regulations.', 'cap-l2-employee-data'),
  cap('cap-l3-employee-self-service', 'Employee Self-service',
    'Enable employees to view and update their personal HR information directly.', 'cap-l2-employee-data'),
  cap('cap-l3-data-compliance', 'Data Compliance',
    'Ensure employee data is handled in accordance with GDPR and employment law.', 'cap-l2-employee-data'),

  // ─── L1: Financial Services ──────────────────────────────────────────────────
  cap('cap-l1-financial-services', 'Financial Services',
    'The ability to manage the financial health, reporting, and obligations of the organisation.'),

  cap('cap-l2-accounting', 'Accounting',
    'Maintains accurate financial records and produces statutory financial statements.',
    'cap-l1-financial-services'),
  cap('cap-l3-general-ledger', 'General Ledger',
    'Record and reconcile all financial transactions in the general ledger.', 'cap-l2-accounting'),
  cap('cap-l3-accounts-payable', 'Accounts Payable',
    'Process and pay supplier invoices accurately and on time.', 'cap-l2-accounting'),
  cap('cap-l3-accounts-receivable', 'Accounts Receivable',
    'Invoice customers and manage the collection of outstanding payments.', 'cap-l2-accounting'),

  cap('cap-l2-controlling', 'Controlling',
    'Monitors financial performance and supports management with cost control insights.',
    'cap-l1-financial-services'),
  cap('cap-l3-cost-centre-management', 'Cost Centre Management',
    'Allocate and track costs against defined cost centres and owners.', 'cap-l2-controlling'),
  cap('cap-l3-budget-control', 'Budget Control',
    'Monitor actual spend versus budget and flag variances for action.', 'cap-l2-controlling'),
  cap('cap-l3-variance-analysis', 'Variance Analysis',
    'Analyse the root causes of budget-to-actual variances.', 'cap-l2-controlling'),

  cap('cap-l2-payments', 'Payments',
    'Executes, reconciles, and secures all inbound and outbound payment transactions.',
    'cap-l1-financial-services'),
  cap('cap-l3-payment-processing', 'Payment Processing',
    'Execute outbound payments and receipts accurately and on schedule.', 'cap-l2-payments'),
  cap('cap-l3-payment-reconciliation', 'Payment Reconciliation',
    'Match payment transactions to ledger entries and resolve discrepancies.', 'cap-l2-payments'),
  cap('cap-l3-payment-fraud-prevention', 'Payment Fraud Prevention',
    'Detect and prevent fraudulent payment activity.', 'cap-l2-payments'),

  cap('cap-l2-tax', 'Tax',
    'Manages compliance with tax obligations across all operating jurisdictions.',
    'cap-l1-financial-services'),
  cap('cap-l3-tax-compliance', 'Tax Compliance',
    'File accurate tax returns and meet all statutory deadlines.', 'cap-l2-tax'),
  cap('cap-l3-tax-reporting', 'Tax Reporting',
    'Produce tax disclosures and supporting schedules for financial statements.', 'cap-l2-tax'),
  cap('cap-l3-transfer-pricing', 'Transfer Pricing',
    'Manage intercompany pricing policies to comply with international tax rules.', 'cap-l2-tax'),

  cap('cap-l2-billing-dunning', 'Billing & Dunning',
    'Manages the invoicing of customers and collection of overdue receivables.',
    'cap-l1-financial-services'),
  cap('cap-l3-invoice-management', 'Invoice Management',
    'Generate, send, and track customer invoices through the billing cycle.', 'cap-l2-billing-dunning'),
  cap('cap-l3-collections-management', 'Collections Management',
    'Chase overdue receivables through structured dunning communications.', 'cap-l2-billing-dunning'),
  cap('cap-l3-revenue-recognition', 'Revenue Recognition',
    'Apply appropriate revenue recognition policies in compliance with accounting standards.', 'cap-l2-billing-dunning'),

  cap('cap-l2-expense-approval', 'Expense Approval',
    'Controls the submission, review, and reimbursement of employee expenses.',
    'cap-l1-financial-services'),
  cap('cap-l3-expense-policy', 'Expense Policy',
    'Define and communicate expense categories, limits, and approvals.', 'cap-l2-expense-approval'),
  cap('cap-l3-expense-submission', 'Expense Submission',
    'Enable employees to submit expense claims with receipts and coding.', 'cap-l2-expense-approval'),
  cap('cap-l3-expense-reimbursement', 'Expense Reimbursement',
    'Process approved expense claims and reimburse employees on schedule.', 'cap-l2-expense-approval'),

  // ─── L1: IT Management ───────────────────────────────────────────────────────
  cap('cap-l1-it-management', 'IT Management',
    'The ability to govern, operate, and secure the internal technology landscape that supports the business.'),

  cap('cap-l2-mobile-device-management', 'Mobile Device Management',
    'Manages and secures employee mobile devices and endpoint hardware.',
    'cap-l1-it-management'),
  cap('cap-l3-device-enrollment', 'Device Enrollment',
    'Onboard and register employee devices into the MDM platform.', 'cap-l2-mobile-device-management'),
  cap('cap-l3-mobile-security', 'Mobile Security',
    'Enforce security policies, remote wipe, and encryption on mobile devices.', 'cap-l2-mobile-device-management'),
  cap('cap-l3-app-management', 'App Management',
    'Distribute and manage approved mobile applications to employee devices.', 'cap-l2-mobile-device-management'),

  cap('cap-l2-enterprise-architecture', 'Enterprise Architecture Management',
    'Governs the alignment between business capabilities and the technology landscape.',
    'cap-l1-it-management'),
  cap('cap-l3-architecture-governance', 'Architecture Governance',
    'Define and enforce architectural standards, patterns, and decision frameworks.', 'cap-l2-enterprise-architecture'),
  cap('cap-l3-technology-roadmap', 'Technology Roadmap',
    'Maintain a forward-looking view of technology investment and retirement.', 'cap-l2-enterprise-architecture'),
  cap('cap-l3-standards-management', 'Standards Management',
    'Document and curate approved technology standards for engineering teams.', 'cap-l2-enterprise-architecture'),

  cap('cap-l2-info-security', 'Information Security & Compliance',
    'Protects company data and systems and ensures regulatory compliance.',
    'cap-l1-it-management'),
  cap('cap-l3-security-policy', 'Security Policy',
    'Define, communicate, and enforce information security policies across the organisation.', 'cap-l2-info-security'),
  cap('cap-l3-compliance-monitoring', 'Compliance Monitoring',
    'Monitor adherence to regulatory requirements and internal controls.', 'cap-l2-info-security'),
  cap('cap-l3-risk-assessment', 'Risk Assessment',
    'Identify, evaluate, and document information security risks.', 'cap-l2-info-security'),

  cap('cap-l2-application-management', 'Application Management',
    'Manages the portfolio of internal business applications through their lifecycle.',
    'cap-l1-it-management'),
  cap('cap-l3-application-lifecycle', 'Application Lifecycle',
    'Govern procurement, deployment, maintenance, and retirement of applications.', 'cap-l2-application-management'),
  cap('cap-l3-saas-management', 'SaaS Management',
    'Track and optimise the portfolio of SaaS subscriptions and licences.', 'cap-l2-application-management'),
  cap('cap-l3-licence-management', 'Licence Management',
    'Manage software licence entitlements, renewals, and compliance.', 'cap-l2-application-management'),

  cap('cap-l2-identity-access', 'Identity & Access Management',
    'Controls who can access which systems and data across the organisation.',
    'cap-l1-it-management'),
  cap('cap-l3-user-provisioning', 'User Provisioning',
    'Automate the creation, modification, and deactivation of user accounts.', 'cap-l2-identity-access'),
  cap('cap-l3-access-control', 'Access Control',
    'Enforce role-based and attribute-based access policies across systems.', 'cap-l2-identity-access'),
  cap('cap-l3-single-sign-on', 'Single Sign-On',
    'Provide unified authentication across the internal application portfolio.', 'cap-l2-identity-access'),

  cap('cap-l2-it-support', 'IT Support',
    'Provides first and second-line technical support to employees.',
    'cap-l1-it-management'),
  cap('cap-l3-help-desk', 'Help Desk',
    'Operate a first-line support function for employee IT issues.', 'cap-l2-it-support'),
  cap('cap-l3-incident-management', 'Incident Management',
    'Triage, escalate, and resolve internal IT incidents within agreed SLAs.', 'cap-l2-it-support'),
  cap('cap-l3-service-request-management', 'Service Request Management',
    'Handle standard employee requests for access, hardware, and software.', 'cap-l2-it-support'),
]

const DEFAULT_CAPABILITY = {
  id:                 'capability-unknown',
  name:               'Capability',
  description:        '',
  parentCapabilityId: null,
  status:             'active',
  createdAt:          null,
  createdBy:          null,
  updatedAt:          null,
  updatedBy:          null,
  subCapabilities:    [],
  owners:             [],
  processes:          [],
  valueStreams:       [],
}

export { CAPABILITIES, DEFAULT_CAPABILITY }
